/*
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class DecisionTreeScopeProvider extends AbstractDecisionTreeScopeProvider {

}
