/*
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DecisionTreeStandaloneSetup extends DecisionTreeStandaloneSetupGenerated {

	public static void doSetup() {
		new DecisionTreeStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
