/*
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDecisionTreeScopeProvider extends DelegatingScopeProvider {
}
