/**
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.decisionTree;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see sdu.mmmi.tamamo.decisionTree.DecisionTreeFactory
 * @model kind="package"
 * @generated
 */
public interface DecisionTreePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "decisionTree";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.mmmi.sdu/tamamo/DecisionTree";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "decisionTree";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DecisionTreePackage eINSTANCE = sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl.init();

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.StartImpl <em>Start</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.StartImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getStart()
   * @generated
   */
  int START = 0;

  /**
   * The feature id for the '<em><b>Decision</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__DECISION = 0;

  /**
   * The feature id for the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__INPUT = 1;

  /**
   * The feature id for the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__PARAMETER = 2;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__RULES = 3;

  /**
   * The feature id for the '<em><b>Conclusion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__CONCLUSION = 4;

  /**
   * The number of structural features of the '<em>Start</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.DecisionImpl <em>Decision</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getDecision()
   * @generated
   */
  int DECISION = 1;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION__TEXT = 0;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION__NEXT = 1;

  /**
   * The feature id for the '<em><b>Nested</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION__NESTED = 2;

  /**
   * The number of structural features of the '<em>Decision</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECISION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.InputImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInput()
   * @generated
   */
  int INPUT = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__NEXT = 1;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputIntImpl <em>Input Int</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.InputIntImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInputInt()
   * @generated
   */
  int INPUT_INT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_INT__NAME = 0;

  /**
   * The number of structural features of the '<em>Input Int</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_INT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputStringImpl <em>Input String</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.InputStringImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInputString()
   * @generated
   */
  int INPUT_STRING = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STRING__NAME = 0;

  /**
   * The number of structural features of the '<em>Input String</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STRING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputBoolImpl <em>Input Bool</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.InputBoolImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInputBool()
   * @generated
   */
  int INPUT_BOOL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_BOOL__NAME = 0;

  /**
   * The number of structural features of the '<em>Input Bool</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_BOOL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.ParameterImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NAME = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__VALUE = 1;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__NEXT = 2;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.RulesImpl <em>Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.RulesImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getRules()
   * @generated
   */
  int RULES = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__LEFT = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__RIGHT = 2;

  /**
   * The feature id for the '<em><b>Affected parameter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__AFFECTED_PARAMETER = 3;

  /**
   * The feature id for the '<em><b>Points</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__POINTS = 4;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__NEXT = 5;

  /**
   * The number of structural features of the '<em>Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.OperatorImpl <em>Operator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.OperatorImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getOperator()
   * @generated
   */
  int OPERATOR = 8;

  /**
   * The number of structural features of the '<em>Operator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATOR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.ConclusionImpl <em>Conclusion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.ConclusionImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getConclusion()
   * @generated
   */
  int CONCLUSION = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION__RIGHT = 2;

  /**
   * The feature id for the '<em><b>Decision</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION__DECISION = 3;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION__NEXT = 4;

  /**
   * The number of structural features of the '<em>Conclusion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.ConclusionNestedImpl <em>Conclusion Nested</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.ConclusionNestedImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getConclusionNested()
   * @generated
   */
  int CONCLUSION_NESTED = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED__LEFT = CONCLUSION__LEFT;

  /**
   * The feature id for the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED__OPERATOR = CONCLUSION__OPERATOR;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED__RIGHT = CONCLUSION__RIGHT;

  /**
   * The feature id for the '<em><b>Decision</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED__DECISION = CONCLUSION__DECISION;

  /**
   * The feature id for the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED__NEXT = CONCLUSION__NEXT;

  /**
   * The feature id for the '<em><b>Parent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED__PARENT = CONCLUSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nested</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED__NESTED = CONCLUSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Conclusion Nested</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONCLUSION_NESTED_FEATURE_COUNT = CONCLUSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.GreaterThanImpl <em>Greater Than</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.GreaterThanImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getGreaterThan()
   * @generated
   */
  int GREATER_THAN = 11;

  /**
   * The number of structural features of the '<em>Greater Than</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_THAN_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.LessThanImpl <em>Less Than</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.LessThanImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getLessThan()
   * @generated
   */
  int LESS_THAN = 12;

  /**
   * The number of structural features of the '<em>Less Than</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_THAN_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.GreaterEqualImpl <em>Greater Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.GreaterEqualImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getGreaterEqual()
   * @generated
   */
  int GREATER_EQUAL = 13;

  /**
   * The number of structural features of the '<em>Greater Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREATER_EQUAL_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link sdu.mmmi.tamamo.decisionTree.impl.LessEqualImpl <em>Less Equal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see sdu.mmmi.tamamo.decisionTree.impl.LessEqualImpl
   * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getLessEqual()
   * @generated
   */
  int LESS_EQUAL = 14;

  /**
   * The number of structural features of the '<em>Less Equal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LESS_EQUAL_FEATURE_COUNT = OPERATOR_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.Start <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Start
   * @generated
   */
  EClass getStart();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Start#getDecision <em>Decision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decision</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Start#getDecision()
   * @see #getStart()
   * @generated
   */
  EReference getStart_Decision();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Start#getInput <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Start#getInput()
   * @see #getStart()
   * @generated
   */
  EReference getStart_Input();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Start#getParameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameter</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Start#getParameter()
   * @see #getStart()
   * @generated
   */
  EReference getStart_Parameter();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Start#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rules</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Start#getRules()
   * @see #getStart()
   * @generated
   */
  EReference getStart_Rules();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Start#getConclusion <em>Conclusion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Conclusion</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Start#getConclusion()
   * @see #getStart()
   * @generated
   */
  EReference getStart_Conclusion();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.Decision <em>Decision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Decision</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Decision
   * @generated
   */
  EClass getDecision();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Decision#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Decision#getText()
   * @see #getDecision()
   * @generated
   */
  EAttribute getDecision_Text();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Decision#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Decision#getNext()
   * @see #getDecision()
   * @generated
   */
  EReference getDecision_Next();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Decision#getNested <em>Nested</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nested</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Decision#getNested()
   * @see #getDecision()
   * @generated
   */
  EReference getDecision_Nested();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Input#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Input#getType()
   * @see #getInput()
   * @generated
   */
  EReference getInput_Type();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Input#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Input#getNext()
   * @see #getInput()
   * @generated
   */
  EReference getInput_Next();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.InputInt <em>Input Int</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Int</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.InputInt
   * @generated
   */
  EClass getInputInt();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.InputInt#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.InputInt#getName()
   * @see #getInputInt()
   * @generated
   */
  EAttribute getInputInt_Name();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.InputString <em>Input String</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input String</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.InputString
   * @generated
   */
  EClass getInputString();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.InputString#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.InputString#getName()
   * @see #getInputString()
   * @generated
   */
  EAttribute getInputString_Name();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.InputBool <em>Input Bool</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Bool</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.InputBool
   * @generated
   */
  EClass getInputBool();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.InputBool#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.InputBool#getName()
   * @see #getInputBool()
   * @generated
   */
  EAttribute getInputBool_Name();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Parameter#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Parameter#getName()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Name();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Parameter#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Parameter#getValue()
   * @see #getParameter()
   * @generated
   */
  EAttribute getParameter_Value();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Parameter#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Parameter#getNext()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Next();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.Rules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rules</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Rules
   * @generated
   */
  EClass getRules();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Rules#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Rules#getLeft()
   * @see #getRules()
   * @generated
   */
  EAttribute getRules_Left();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Rules#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Rules#getOperator()
   * @see #getRules()
   * @generated
   */
  EReference getRules_Operator();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Rules#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Rules#getRight()
   * @see #getRules()
   * @generated
   */
  EAttribute getRules_Right();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Rules#getAffected_parameter <em>Affected parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Affected parameter</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Rules#getAffected_parameter()
   * @see #getRules()
   * @generated
   */
  EAttribute getRules_Affected_parameter();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Rules#getPoints <em>Points</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Points</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Rules#getPoints()
   * @see #getRules()
   * @generated
   */
  EAttribute getRules_Points();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Rules#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Rules#getNext()
   * @see #getRules()
   * @generated
   */
  EReference getRules_Next();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.Operator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operator</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Operator
   * @generated
   */
  EClass getOperator();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.Conclusion <em>Conclusion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conclusion</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Conclusion
   * @generated
   */
  EClass getConclusion();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Conclusion#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Conclusion#getLeft()
   * @see #getConclusion()
   * @generated
   */
  EAttribute getConclusion_Left();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Conclusion#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Operator</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Conclusion#getOperator()
   * @see #getConclusion()
   * @generated
   */
  EReference getConclusion_Operator();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.Conclusion#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Conclusion#getRight()
   * @see #getConclusion()
   * @generated
   */
  EAttribute getConclusion_Right();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Conclusion#getDecision <em>Decision</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decision</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Conclusion#getDecision()
   * @see #getConclusion()
   * @generated
   */
  EReference getConclusion_Decision();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.Conclusion#getNext <em>Next</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Next</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.Conclusion#getNext()
   * @see #getConclusion()
   * @generated
   */
  EReference getConclusion_Next();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.ConclusionNested <em>Conclusion Nested</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Conclusion Nested</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.ConclusionNested
   * @generated
   */
  EClass getConclusionNested();

  /**
   * Returns the meta object for the attribute '{@link sdu.mmmi.tamamo.decisionTree.ConclusionNested#getParent <em>Parent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Parent</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.ConclusionNested#getParent()
   * @see #getConclusionNested()
   * @generated
   */
  EAttribute getConclusionNested_Parent();

  /**
   * Returns the meta object for the containment reference '{@link sdu.mmmi.tamamo.decisionTree.ConclusionNested#getNested <em>Nested</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nested</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.ConclusionNested#getNested()
   * @see #getConclusionNested()
   * @generated
   */
  EReference getConclusionNested_Nested();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.GreaterThan <em>Greater Than</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greater Than</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.GreaterThan
   * @generated
   */
  EClass getGreaterThan();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.LessThan <em>Less Than</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less Than</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.LessThan
   * @generated
   */
  EClass getLessThan();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.GreaterEqual <em>Greater Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greater Equal</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.GreaterEqual
   * @generated
   */
  EClass getGreaterEqual();

  /**
   * Returns the meta object for class '{@link sdu.mmmi.tamamo.decisionTree.LessEqual <em>Less Equal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Less Equal</em>'.
   * @see sdu.mmmi.tamamo.decisionTree.LessEqual
   * @generated
   */
  EClass getLessEqual();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DecisionTreeFactory getDecisionTreeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.StartImpl <em>Start</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.StartImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getStart()
     * @generated
     */
    EClass START = eINSTANCE.getStart();

    /**
     * The meta object literal for the '<em><b>Decision</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START__DECISION = eINSTANCE.getStart_Decision();

    /**
     * The meta object literal for the '<em><b>Input</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START__INPUT = eINSTANCE.getStart_Input();

    /**
     * The meta object literal for the '<em><b>Parameter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START__PARAMETER = eINSTANCE.getStart_Parameter();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START__RULES = eINSTANCE.getStart_Rules();

    /**
     * The meta object literal for the '<em><b>Conclusion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START__CONCLUSION = eINSTANCE.getStart_Conclusion();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.DecisionImpl <em>Decision</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getDecision()
     * @generated
     */
    EClass DECISION = eINSTANCE.getDecision();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECISION__TEXT = eINSTANCE.getDecision_Text();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECISION__NEXT = eINSTANCE.getDecision_Next();

    /**
     * The meta object literal for the '<em><b>Nested</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECISION__NESTED = eINSTANCE.getDecision_Nested();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.InputImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT__TYPE = eINSTANCE.getInput_Type();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT__NEXT = eINSTANCE.getInput_Next();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputIntImpl <em>Input Int</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.InputIntImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInputInt()
     * @generated
     */
    EClass INPUT_INT = eINSTANCE.getInputInt();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_INT__NAME = eINSTANCE.getInputInt_Name();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputStringImpl <em>Input String</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.InputStringImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInputString()
     * @generated
     */
    EClass INPUT_STRING = eINSTANCE.getInputString();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_STRING__NAME = eINSTANCE.getInputString_Name();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.InputBoolImpl <em>Input Bool</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.InputBoolImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getInputBool()
     * @generated
     */
    EClass INPUT_BOOL = eINSTANCE.getInputBool();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_BOOL__NAME = eINSTANCE.getInputBool_Name();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.ParameterImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__NAME = eINSTANCE.getParameter_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAMETER__VALUE = eINSTANCE.getParameter_Value();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__NEXT = eINSTANCE.getParameter_Next();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.RulesImpl <em>Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.RulesImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getRules()
     * @generated
     */
    EClass RULES = eINSTANCE.getRules();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULES__LEFT = eINSTANCE.getRules_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__OPERATOR = eINSTANCE.getRules_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULES__RIGHT = eINSTANCE.getRules_Right();

    /**
     * The meta object literal for the '<em><b>Affected parameter</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULES__AFFECTED_PARAMETER = eINSTANCE.getRules_Affected_parameter();

    /**
     * The meta object literal for the '<em><b>Points</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULES__POINTS = eINSTANCE.getRules_Points();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__NEXT = eINSTANCE.getRules_Next();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.OperatorImpl <em>Operator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.OperatorImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getOperator()
     * @generated
     */
    EClass OPERATOR = eINSTANCE.getOperator();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.ConclusionImpl <em>Conclusion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.ConclusionImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getConclusion()
     * @generated
     */
    EClass CONCLUSION = eINSTANCE.getConclusion();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCLUSION__LEFT = eINSTANCE.getConclusion_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCLUSION__OPERATOR = eINSTANCE.getConclusion_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCLUSION__RIGHT = eINSTANCE.getConclusion_Right();

    /**
     * The meta object literal for the '<em><b>Decision</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCLUSION__DECISION = eINSTANCE.getConclusion_Decision();

    /**
     * The meta object literal for the '<em><b>Next</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCLUSION__NEXT = eINSTANCE.getConclusion_Next();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.ConclusionNestedImpl <em>Conclusion Nested</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.ConclusionNestedImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getConclusionNested()
     * @generated
     */
    EClass CONCLUSION_NESTED = eINSTANCE.getConclusionNested();

    /**
     * The meta object literal for the '<em><b>Parent</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONCLUSION_NESTED__PARENT = eINSTANCE.getConclusionNested_Parent();

    /**
     * The meta object literal for the '<em><b>Nested</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONCLUSION_NESTED__NESTED = eINSTANCE.getConclusionNested_Nested();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.GreaterThanImpl <em>Greater Than</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.GreaterThanImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getGreaterThan()
     * @generated
     */
    EClass GREATER_THAN = eINSTANCE.getGreaterThan();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.LessThanImpl <em>Less Than</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.LessThanImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getLessThan()
     * @generated
     */
    EClass LESS_THAN = eINSTANCE.getLessThan();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.GreaterEqualImpl <em>Greater Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.GreaterEqualImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getGreaterEqual()
     * @generated
     */
    EClass GREATER_EQUAL = eINSTANCE.getGreaterEqual();

    /**
     * The meta object literal for the '{@link sdu.mmmi.tamamo.decisionTree.impl.LessEqualImpl <em>Less Equal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see sdu.mmmi.tamamo.decisionTree.impl.LessEqualImpl
     * @see sdu.mmmi.tamamo.decisionTree.impl.DecisionTreePackageImpl#getLessEqual()
     * @generated
     */
    EClass LESS_EQUAL = eINSTANCE.getLessEqual();

  }

} //DecisionTreePackage
