/**
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.decisionTree;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Decision</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Decision#getText <em>Text</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Decision#getNext <em>Next</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Decision#getNested <em>Nested</em>}</li>
 * </ul>
 *
 * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getDecision()
 * @model
 * @generated
 */
public interface Decision extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getDecision_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Decision#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference.
   * @see #setNext(Decision)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getDecision_Next()
   * @model containment="true"
   * @generated
   */
  Decision getNext();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Decision#getNext <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' containment reference.
   * @see #getNext()
   * @generated
   */
  void setNext(Decision value);

  /**
   * Returns the value of the '<em><b>Nested</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nested</em>' containment reference.
   * @see #setNested(Decision)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getDecision_Nested()
   * @model containment="true"
   * @generated
   */
  Decision getNested();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Decision#getNested <em>Nested</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nested</em>' containment reference.
   * @see #getNested()
   * @generated
   */
  void setNested(Decision value);

} // Decision
