/**
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.decisionTree;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Less Equal</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getLessEqual()
 * @model
 * @generated
 */
public interface LessEqual extends Operator
{
} // LessEqual
