/**
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.decisionTree;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getOperator()
 * @model
 * @generated
 */
public interface Operator extends EObject
{
} // Operator
