/**
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.decisionTree;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Parameter#getName <em>Name</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Parameter#getValue <em>Value</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Parameter#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getParameter_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Parameter#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getParameter_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Parameter#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference.
   * @see #setNext(Parameter)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getParameter_Next()
   * @model containment="true"
   * @generated
   */
  Parameter getNext();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Parameter#getNext <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' containment reference.
   * @see #getNext()
   * @generated
   */
  void setNext(Parameter value);

} // Parameter
