/**
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.decisionTree;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rules</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Rules#getLeft <em>Left</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Rules#getOperator <em>Operator</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Rules#getRight <em>Right</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Rules#getAffected_parameter <em>Affected parameter</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Rules#getPoints <em>Points</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Rules#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getRules()
 * @model
 * @generated
 */
public interface Rules extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' attribute.
   * @see #setLeft(String)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getRules_Left()
   * @model
   * @generated
   */
  String getLeft();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Rules#getLeft <em>Left</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' attribute.
   * @see #getLeft()
   * @generated
   */
  void setLeft(String value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' containment reference.
   * @see #setOperator(Operator)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getRules_Operator()
   * @model containment="true"
   * @generated
   */
  Operator getOperator();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Rules#getOperator <em>Operator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' containment reference.
   * @see #getOperator()
   * @generated
   */
  void setOperator(Operator value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' attribute.
   * @see #setRight(String)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getRules_Right()
   * @model
   * @generated
   */
  String getRight();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Rules#getRight <em>Right</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' attribute.
   * @see #getRight()
   * @generated
   */
  void setRight(String value);

  /**
   * Returns the value of the '<em><b>Affected parameter</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Affected parameter</em>' attribute.
   * @see #setAffected_parameter(String)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getRules_Affected_parameter()
   * @model
   * @generated
   */
  String getAffected_parameter();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Rules#getAffected_parameter <em>Affected parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Affected parameter</em>' attribute.
   * @see #getAffected_parameter()
   * @generated
   */
  void setAffected_parameter(String value);

  /**
   * Returns the value of the '<em><b>Points</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' attribute.
   * @see #setPoints(int)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getRules_Points()
   * @model
   * @generated
   */
  int getPoints();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Rules#getPoints <em>Points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Points</em>' attribute.
   * @see #getPoints()
   * @generated
   */
  void setPoints(int value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference.
   * @see #setNext(Rules)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getRules_Next()
   * @model containment="true"
   * @generated
   */
  Rules getNext();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Rules#getNext <em>Next</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Next</em>' containment reference.
   * @see #getNext()
   * @generated
   */
  void setNext(Rules value);

} // Rules
