/**
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.decisionTree;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Start#getDecision <em>Decision</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Start#getInput <em>Input</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Start#getParameter <em>Parameter</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Start#getRules <em>Rules</em>}</li>
 *   <li>{@link sdu.mmmi.tamamo.decisionTree.Start#getConclusion <em>Conclusion</em>}</li>
 * </ul>
 *
 * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getStart()
 * @model
 * @generated
 */
public interface Start extends EObject
{
  /**
   * Returns the value of the '<em><b>Decision</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decision</em>' containment reference.
   * @see #setDecision(Decision)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getStart_Decision()
   * @model containment="true"
   * @generated
   */
  Decision getDecision();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Start#getDecision <em>Decision</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decision</em>' containment reference.
   * @see #getDecision()
   * @generated
   */
  void setDecision(Decision value);

  /**
   * Returns the value of the '<em><b>Input</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input</em>' containment reference.
   * @see #setInput(Input)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getStart_Input()
   * @model containment="true"
   * @generated
   */
  Input getInput();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Start#getInput <em>Input</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Input</em>' containment reference.
   * @see #getInput()
   * @generated
   */
  void setInput(Input value);

  /**
   * Returns the value of the '<em><b>Parameter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameter</em>' containment reference.
   * @see #setParameter(Parameter)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getStart_Parameter()
   * @model containment="true"
   * @generated
   */
  Parameter getParameter();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Start#getParameter <em>Parameter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameter</em>' containment reference.
   * @see #getParameter()
   * @generated
   */
  void setParameter(Parameter value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference.
   * @see #setRules(Rules)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getStart_Rules()
   * @model containment="true"
   * @generated
   */
  Rules getRules();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Start#getRules <em>Rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rules</em>' containment reference.
   * @see #getRules()
   * @generated
   */
  void setRules(Rules value);

  /**
   * Returns the value of the '<em><b>Conclusion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conclusion</em>' containment reference.
   * @see #setConclusion(Conclusion)
   * @see sdu.mmmi.tamamo.decisionTree.DecisionTreePackage#getStart_Conclusion()
   * @model containment="true"
   * @generated
   */
  Conclusion getConclusion();

  /**
   * Sets the value of the '{@link sdu.mmmi.tamamo.decisionTree.Start#getConclusion <em>Conclusion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conclusion</em>' containment reference.
   * @see #getConclusion()
   * @generated
   */
  void setConclusion(Conclusion value);

} // Start
