/*
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sdu.mmmi.tamamo.parser.antlr.internal.InternalDecisionTreeParser;
import sdu.mmmi.tamamo.services.DecisionTreeGrammarAccess;

public class DecisionTreeParser extends AbstractAntlrParser {

	@Inject
	private DecisionTreeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDecisionTreeParser createParser(XtextTokenStream stream) {
		return new InternalDecisionTreeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Start";
	}

	public DecisionTreeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DecisionTreeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
