/*
 * generated by Xtext 2.24.0
 */
package sdu.mmmi.tamamo.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DecisionTreeAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("sdu/mmmi/tamamo/parser/antlr/internal/InternalDecisionTree.tokens");
	}
}
